FROM mcr.microsoft.com/playwright/python:v1.44.0-jammy

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt
RUN playwright install chromium

COPY bot_agendamentos.py .
COPY scheduler_agendamentos.py .

CMD ["python", "bot_agendamentos.py"]
